services:
  # https://hub.docker.com/r/bitnami/mongodb
  mongodb:
    image: docker.io/bitnami/mongodb:8.0
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=toor
      - MONGODB_USER=serviceuser
      - MONGODB_USER_PASSWORD=password
      - MONGODB_DATABASE=polldb

  # https://hub.docker.com/r/bitnami/postgresql
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=keycloakdb
      - POSTGRESQL_USERNAME=keycloakdbuser
      - POSTGRESQL_PASSWORD=dbpassword
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  # https://hub.docker.com/r/bitnami/keycloak
  # admin username: user password: bitnami
  keycloak:
    image: bitnami/keycloak:25
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_DATABASE_USER=keycloakdbuser
      - KEYCLOAK_DATABASE_PASSWORD=dbpassword
      - KEYCLOAK_DATABASE_NAME=keycloakdb
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongodb_data:
  postgres_data: